version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-di-cri-experian-fraud-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "dev-di-cri-experian-fraud-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
